spring:
  datasource:
    username: root
    password: Ire7758521
    url: jdbc:mysql://localhost:3306/booksmate?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
